AWSTemplateFormatVersion: 2010-09-09
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.17.128.0/20
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: HiroseVPCfromCF
  subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref myVPC
      CidrBlock: 172.17.128.0/24
      Tags:
        - Key: Name
          Value: HiroseSubnet
  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: GroupName-SG
      GroupDescription: "GroupDescription-SG"
      VpcId: !Ref myVPC
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: HiroseSG
        