AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VPCCIDR:
    Description: CIDR Block for VPC
    Type: String
    Default: 172.17.128.0/20
  Name:
    Description: Tags Name for VPC
    Type: String
    Default: Hirose2VPCfromCF

Resources:
  HiroseVPC2:
    Type: AWS::EC2::VPC
    Properties:
     CidrBlock: !Ref VPCCIDR
     EnableDnsSupport: true
     Tags:
       - Key: Name
         Value: !Ref Name