AWSTemplateFormatVersion: 2010-09-09

Mappings: 
  RegionMap:
    ap-northeast-1:
      "AMI": "ami-imageID"
    ap-southeast-1:
      "AMI": "ami-imageID"
    us-east-1:
      "AMI": "ami-imageID"
#各リージョンにマッピングさせるためのAMIを事前に作成して、AMIIDを入力

Resources: 

myEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    ImageId:  !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
    InstanceType: t2.micro 
    Tags:
      - Key: Name
        Value: Hirose Server
