AWSTemplateFormatVersion: 2010-09-09
Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: "キーペア名"
      ImageId: "AMIID"
      InstanceType: "インスタンスタイプ"
      Monitoring: false
      SecurityGroupIds:
        - !ImportValue SG1Name
      SubnetId: !ImportValue Subnet1Name
      Tags:
        - Key: key
          Value: value