AWSTemplateFormatVersion: 2010-09-09
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.17.128.0/20
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: HiroseVPCfromCF
  subnetName1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref myVPC
      CidrBlock: 172.17.128.0/24
      Tags:
        - Key: Name
          Value: HiroseSubnet-1a
  subnetName2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref myVPC
      CidrBlock: 172.17.128.16/24
      Tags:
        - Key: Name
          Value: HiroseSubnet-1c

  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: GroupName-SG
      GroupDescription: "GroupDescription-SG"
      VpcId: !Ref myVPC
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: HiroseSG
Outputs:
  Subnet1:
    Value: !Ref subnetName1
    Export:
      Name: Subnet-1a-Name
  Subnet2:
    Value: !Ref subnetName2
    Export:
      Name: Subnet-1c-Name

  SG1:
    Value: !Ref secGroupName
    Export:
      Name: SG1Name