Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for EC2
      GroupName: SG-hirose
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: SGForEC2
      VpcId: !ImportValue VPC-hirose

Outputs:
  MySecurityGroup:
    Description: The security group ID to use for public web servers
    Value: 
      'Fn::GetAtt':
        - SecurityGroup
        - GroupId
    Export: 
      Name: 
        'Fn::Sub': '${AWS::StackName}-SecurityGroupID'
