Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for EC2
      GroupName: SG-hirose
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: SGForEC2

Outputs:
  MySecurityGroup:
    Value: !Ref SecurityGroup
    Export: 
      Name: SG-hirose-80
