Resources:
 myEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: awsc-key-285-hirose-01
    ImageId: ami-022282eb775c6a4fa
    InstanceType: t2.micro 
    Monitoring: false
    SecurityGroupIds:
      - !ImportValue SG-hirose
    VpcId:
      - !ImportValue VPC-hirose   
    SubnetId:
      -  !ImportValue PubSubName-1a

    Tags:
      - Key: Name
        Value: hirose-ec2


# EIP付与が必要
myEIP:
  Type: AWS::EC2::EIP
  Properties:
    InstanceId: !Ref myEC2Instance