Resources:
 myEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: awsc-key-285-hirose-01
    ImageId: ami-022282eb775c6a4fa
    InstanceType: t2.micro 
    Monitoring: false
    SecurityGroupIds:
      - !ImportValue SG-hirose

    Tags:
      - Key: key
        Value: value


# EIP,Nameタグの付与が必要