myEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: 
    DisableApiTermination: 
    ImageId: 
    InstanceType: t2.micro 
    Monitoring: false
    SecurityGroupIds:
      - !ImportValue SG-hirose

    Tags:
      - Key: key
        Value: value